version: '3'
services:
  postgress: 
      image: postgres:13
      container_name: postgres_db
      enviroment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - airflow_network


networks:
  airflow_networks:
    external: false
#This will create a new network if it does not exist


